// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.kmpandroidlint

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

/**
 * Consumes `fakeUserRepository`, generated by Fakt into this module's `commonTest` source set, so
 * the generated source dir is a real input of the test/lint pipeline. Together with the AGP lint
 * run this gives end-to-end coverage of the #129 scenario under Gradle 9.6.1.
 */
class UserRepositoryTest {

    @Test
    fun `GIVEN fake user repository WHEN using defaults THEN compiles and runs`() {
        val fake = fakeUserRepository {}
        assertNotNull(fake)
        assertNotNull(fake.currentUser)
    }

    @Test
    fun `GIVEN fake user repository WHEN customizing behavior THEN applies correctly`() {
        val fake =
            fakeUserRepository {
                currentUser { "Alice" }
                getUser { id -> "User-$id" }
                findUsers { _, _ -> listOf("Alice", "Bob") }
            }
        assertEquals("Alice", fake.currentUser)
        assertEquals("User-42", fake.getUser(42))
        assertEquals(listOf("Alice", "Bob"), fake.findUsers("test", 10))
    }
}
