// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.compiler.ir.generation

import com.rsicarelli.fakt.codegen.extensions.AnnotationSpec
import com.rsicarelli.fakt.codegen.extensions.FactoryFunctionSpec
import com.rsicarelli.fakt.codegen.extensions.MethodSpec
import com.rsicarelli.fakt.codegen.extensions.PropertySpec
import com.rsicarelli.fakt.codegen.extensions.generateCallHistoryDeclarations
import com.rsicarelli.fakt.codegen.extensions.generateCompleteFake
import com.rsicarelli.fakt.codegen.extensions.generateFactoryFunction
import com.rsicarelli.fakt.codegen.model.CodeFile
import com.rsicarelli.fakt.compiler.core.types.TypeResolution
import com.rsicarelli.fakt.compiler.fir.metadata.FirVisibility
import com.rsicarelli.fakt.compiler.ir.analysis.AnnotationAnalysis
import com.rsicarelli.fakt.compiler.ir.analysis.ClassAnalysis
import com.rsicarelli.fakt.compiler.ir.analysis.InterfaceAnalysis

/**
 * Holds the generated code pieces from the implementation generator.
 *
 * @property implementationFile CodeFile with package, imports, implementation class, and call history components
 * @property factoryFunction Generated factory function code (string)
 */
internal data class GeneratedFakeCode(
    val implementationFile: CodeFile,
    val factoryFunction: String,
)

/**
 * Implementation generator for fake classes and factory functions.
 *
 * Uses type-safe DSL for clean, composable code generation.
 */
internal class ImplementationGenerator(
    private val typeResolver: TypeResolution,
) {
    /**
     * Generates fake implementation and factory for an interface.
     *
     * Returns implementation CodeFile and factory function string.
     *
     * @param analysis The analyzed interface metadata
     * @param packageName The package name for the generated code
     * @param imports Additional imports required by the interface (from ImportResolver)
     * @return GeneratedFakeCode with CodeFile and factory string
     */
    fun generateImplementation(
        analysis: InterfaceAnalysis,
        packageName: String,
        imports: List<String> = emptyList(),
    ): GeneratedFakeCode {
        // Map IR analysis to codegen models
        val (methods, properties) = analysis.toCodegenSpecs(typeResolver)

        // Convert annotations to codegen specs
        val annotationSpecs = analysis.annotations.map { it.toAnnotationSpec() }

        // Generate implementation using DSL with visibility for explicitApi() support
        var implementationFile =
            generateCompleteFake(
                packageName = packageName,
                interfaceName = analysis.interfaceName,
                methods = methods,
                properties = properties,
                imports = imports,
                header = "Generated by Fakt\n// Interface: ${analysis.interfaceName}",
                typeParameters = analysis.typeParameters,
                visibility = analysis.visibility,
                annotations = annotationSpecs,
            )

        // Generate factory function with visibility for explicitApi() support
        val factoryFunction =
            generateFactoryFunction(
                FactoryFunctionSpec(
                    interfaceName = analysis.interfaceName,
                    typeParameters = analysis.typeParameters,
                    visibility = analysis.visibility,
                    annotations = annotationSpecs,
                    methods = methods,
                    properties = properties,
                ),
            )

        // Generate call history components using DSL and add to implementation file
        val fakeClassName = "Fake${analysis.interfaceName}Impl"
        val callHistoryDeclarations =
            generateCallHistoryDeclarations(
                fakeClassName = fakeClassName,
                interfaceName = analysis.interfaceName,
                methods = methods,
                visibility = analysis.visibility,
                classTypeParameters = analysis.typeParameters,
            )

        // Add call history declarations to the implementation file
        callHistoryDeclarations.forEach { declaration ->
            implementationFile = implementationFile.addDeclaration(declaration)
        }

        return GeneratedFakeCode(
            implementationFile = implementationFile,
            factoryFunction = factoryFunction,
        )
    }

    /**
     * Generates fake implementation and factory for a class.
     *
     * Returns implementation CodeFile and factory function string.
     *
     * @param analysis The analyzed class metadata
     * @param packageName The package name for the generated code
     * @param imports Additional imports required by the class (from ImportResolver)
     * @return GeneratedFakeCode with CodeFile and factory string
     */
    fun generateClassFake(
        analysis: ClassAnalysis,
        packageName: String,
        imports: List<String> = emptyList(),
    ): GeneratedFakeCode {
        val (methodSpecs, propertySpecs) = analysis.toMemberSpecs(typeResolver)
        val annotationSpecs = analysis.annotations.map { it.toAnnotationSpec() }

        // Generate implementation using DSL with visibility for explicitApi() support
        var implementationFile =
            generateCompleteFake(
                packageName = packageName,
                interfaceName = analysis.className,
                methods = methodSpecs,
                properties = propertySpecs,
                imports = imports,
                header = "Generated by Fakt\n// Class: ${analysis.className}",
                typeParameters = analysis.typeParameters,
                isClass = true,
                visibility = analysis.visibility,
                annotations = annotationSpecs,
            )

        // Generate factory function with visibility for explicitApi() support
        val factoryFunction =
            generateFactoryFunction(
                FactoryFunctionSpec(
                    interfaceName = analysis.className,
                    typeParameters = analysis.typeParameters,
                    visibility = analysis.visibility,
                    annotations = annotationSpecs,
                    methods = methodSpecs,
                    properties = propertySpecs,
                ),
            )

        // Generate call history components using DSL and add to implementation file
        val fakeClassName = "Fake${analysis.className}Impl"
        val callHistoryDeclarations =
            generateCallHistoryDeclarations(
                fakeClassName = fakeClassName,
                interfaceName = analysis.className,
                methods = methodSpecs,
                visibility = analysis.visibility,
                classTypeParameters = analysis.typeParameters,
            )

        // Add call history declarations to the implementation file
        callHistoryDeclarations.forEach { declaration ->
            implementationFile = implementationFile.addDeclaration(declaration)
        }

        return GeneratedFakeCode(
            implementationFile = implementationFile,
            factoryFunction = factoryFunction,
        )
    }
}

/**
 * Convert AnnotationAnalysis to AnnotationSpec for code generation.
 */
private fun AnnotationAnalysis.toAnnotationSpec(): AnnotationSpec =
    AnnotationSpec(
        simpleName = simpleName,
        fullyQualifiedName = fullyQualifiedName,
        arguments = renderedArguments,
        isOptInMarker = isOptInMarker,
    )

/**
 * Convert ClassAnalysis members to method and property specs.
 */
private fun ClassAnalysis.toMemberSpecs(typeResolver: TypeResolution): Pair<List<MethodSpec>, List<PropertySpec>> {
    val methodSpecs =
        abstractMethods.map { it.toMethodSpec(typeResolver).copy(isAbstract = true) } +
            openMethods.map { it.toMethodSpec(typeResolver).copy(isAbstract = false) }
    val propertySpecs =
        abstractProperties.map { it.toPropertySpec(typeResolver).copy(isAbstract = true) } +
            openProperties.map { it.toPropertySpec(typeResolver).copy(isAbstract = false) }
    return methodSpecs to propertySpecs
}
