// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.compiler.ir.generation

import com.rsicarelli.fakt.codegen.builder.parseType
import com.rsicarelli.fakt.codegen.extensions.AnnotationSpec
import com.rsicarelli.fakt.codegen.extensions.FactoryFunctionSpec
import com.rsicarelli.fakt.codegen.extensions.MethodSpec
import com.rsicarelli.fakt.codegen.extensions.PropertySpec
import com.rsicarelli.fakt.codegen.extensions.generateCallHistoryDeclarations
import com.rsicarelli.fakt.codegen.extensions.generateCompleteFake
import com.rsicarelli.fakt.codegen.extensions.generateFactoryFunctionCodeFile
import com.rsicarelli.fakt.codegen.model.CodeFile
import com.rsicarelli.fakt.codegen.renderer.render
import com.rsicarelli.fakt.codegen.strategy.DefaultValueResolver
import com.rsicarelli.fakt.compiler.core.types.TypeResolution
import com.rsicarelli.fakt.compiler.ir.analysis.AnnotationAnalysis
import com.rsicarelli.fakt.compiler.ir.analysis.ClassAnalysis
import com.rsicarelli.fakt.compiler.ir.analysis.InterfaceAnalysis

/**
 * Holds the generated code pieces from the implementation generator.
 *
 * Uses CodeFile for type-safe, composable code generation.
 *
 * @property implementationFile CodeFile with package, imports, implementation class, and call
 *   history components
 * @property factoryFunction CodeFile containing the factory function
 */
internal data class GeneratedFakeCode(
    val implementationFile: CodeFile,
    val factoryFunction: CodeFile,
)

/**
 * Implementation generator for fake classes and factory functions.
 *
 * Uses type-safe DSL for clean, composable code generation.
 */
internal class ImplementationGenerator(private val typeResolver: TypeResolution) {
    /**
     * Generates fake implementation and factory for an interface.
     *
     * Returns implementation and factory as CodeFiles for type-safe composition.
     *
     * @param analysis The analyzed interface metadata
     * @param packageName The package name for the generated code
     * @param imports Additional imports required by the interface (from ImportResolver)
     * @return GeneratedFakeCode with CodeFiles for implementation and factory
     */
    fun generateImplementation(
        analysis: InterfaceAnalysis,
        packageName: String,
        imports: List<String> = emptyList(),
    ): GeneratedFakeCode {
        // Map IR analysis to codegen models
        val (methods, properties) = analysis.toCodegenSpecs(typeResolver)

        // Convert annotations to codegen specs
        val annotationSpecs = analysis.annotations.map { it.toAnnotationSpec() }

        // Generate implementation using DSL with visibility for explicitApi() support
        var implementationFile =
            generateCompleteFake(
                packageName = packageName,
                interfaceName = analysis.interfaceName,
                superTypeName = analysis.qualifiedSourceName,
                methods = methods,
                properties = properties,
                imports = imports,
                header = "Generated by Fakt\n// Interface: ${analysis.qualifiedSourceName}",
                typeParameters = analysis.typeParameters,
                visibility = analysis.visibility,
                annotations = annotationSpecs,
                generateCallHistory = analysis.generateCallHistory,
                generateMutableBehaviors = analysis.generateMutableBehaviors,
            )

        // Generate factory function CodeFile with visibility for explicitApi() support
        val factoryFunction =
            generateFactoryFunctionCodeFile(
                FactoryFunctionSpec(
                    interfaceName = analysis.interfaceName,
                    superTypeName = analysis.qualifiedSourceName,
                    typeParameters = analysis.typeParameters,
                    visibility = analysis.visibility,
                    annotations = annotationSpecs,
                    methods = methods,
                    properties = properties,
                )
            )

        // Generate call history components using DSL and add to implementation file
        // Only if call history is enabled for this fake
        if (analysis.generateCallHistory) {
            val fakeClassName = "Fake${analysis.interfaceName}Impl"
            val callHistoryDeclarations =
                generateCallHistoryDeclarations(
                    fakeClassName = fakeClassName,
                    interfaceName = analysis.interfaceName,
                    methods = methods,
                    visibility = analysis.visibility,
                    classTypeParameters = analysis.typeParameters,
                )

            // Add call history declarations to the implementation file
            callHistoryDeclarations.forEach { declaration ->
                implementationFile = implementationFile.addDeclaration(declaration)
            }
        }

        return GeneratedFakeCode(
            implementationFile = implementationFile,
            factoryFunction = factoryFunction,
        )
    }

    /**
     * Generates fake implementation and factory for a class.
     *
     * Returns implementation and factory as CodeFiles for type-safe composition.
     *
     * @param analysis The analyzed class metadata
     * @param packageName The package name for the generated code
     * @param imports Additional imports required by the class (from ImportResolver)
     * @return GeneratedFakeCode with CodeFiles for implementation and factory
     */
    fun generateClassFake(
        analysis: ClassAnalysis,
        packageName: String,
        imports: List<String> = emptyList(),
    ): GeneratedFakeCode {
        val (methodSpecs, propertySpecs) = analysis.toMemberSpecs(typeResolver)
        val annotationSpecs = analysis.annotations.map { it.toAnnotationSpec() }

        // Build super constructor call with default values for required params
        val superConstructorCall = buildSuperConstructorCall(analysis)

        // Generate implementation using DSL with visibility for explicitApi() support
        var implementationFile =
            generateCompleteFake(
                packageName = packageName,
                interfaceName = analysis.className,
                superTypeName = analysis.qualifiedSourceName,
                methods = methodSpecs,
                properties = propertySpecs,
                imports = imports,
                header = "Generated by Fakt\n// Class: ${analysis.qualifiedSourceName}",
                typeParameters = analysis.typeParameters,
                isClass = true,
                visibility = analysis.visibility,
                annotations = annotationSpecs,
                generateCallHistory = analysis.generateCallHistory,
                generateMutableBehaviors = analysis.generateMutableBehaviors,
                superConstructorCall = superConstructorCall,
            )

        // Generate factory function CodeFile with visibility for explicitApi() support
        val factoryFunction =
            generateFactoryFunctionCodeFile(
                FactoryFunctionSpec(
                    interfaceName = analysis.className,
                    superTypeName = analysis.qualifiedSourceName,
                    typeParameters = analysis.typeParameters,
                    visibility = analysis.visibility,
                    annotations = annotationSpecs,
                    methods = methodSpecs,
                    properties = propertySpecs,
                )
            )

        // Generate call history components using DSL and add to implementation file
        // Only if call history is enabled for this fake
        if (analysis.generateCallHistory) {
            val fakeClassName = "Fake${analysis.className}Impl"
            val callHistoryDeclarations =
                generateCallHistoryDeclarations(
                    fakeClassName = fakeClassName,
                    interfaceName = analysis.className,
                    methods = methodSpecs,
                    visibility = analysis.visibility,
                    classTypeParameters = analysis.typeParameters,
                )

            // Add call history declarations to the implementation file
            callHistoryDeclarations.forEach { declaration ->
                implementationFile = implementationFile.addDeclaration(declaration)
            }
        }

        return GeneratedFakeCode(
            implementationFile = implementationFile,
            factoryFunction = factoryFunction,
        )
    }

    /**
     * Builds the super constructor call arguments for abstract class fakes.
     *
     * Generates default values for required constructor parameters using the same
     * DefaultValueResolver strategy used for method return types. Parameters with defaults are
     * omitted (the class's own defaults apply).
     *
     * Uses pre-extracted [ClassAnalysis.constructorParameters] — no direct IR access needed.
     *
     * Example: `DataFormatter<T>(locale: String, precision: Int = 2)` → `locale = ""` (precision
     * omitted — has default)
     */
    private fun buildSuperConstructorCall(analysis: ClassAnalysis): String {
        val params = analysis.constructorParameters.filter { !it.hasDefault }
        if (params.isEmpty()) return ""

        val resolver = DefaultValueResolver()
        return params.joinToString(", ") { param ->
            val parsedType = parseType(param.typeString)
            val defaultExpr = resolver.resolve(parsedType).render()
            "${param.name} = $defaultExpr"
        }
    }
}

/** Convert AnnotationAnalysis to AnnotationSpec for code generation. */
private fun AnnotationAnalysis.toAnnotationSpec(): AnnotationSpec =
    AnnotationSpec(
        simpleName = simpleName,
        fullyQualifiedName = fullyQualifiedName,
        arguments = renderedArguments,
        isOptInMarker = isOptInMarker,
    )

/** Convert ClassAnalysis members to method and property specs. */
private fun ClassAnalysis.toMemberSpecs(
    typeResolver: TypeResolution
): Pair<List<MethodSpec>, List<PropertySpec>> {
    val methodSpecs =
        abstractMethods.map { it.toMethodSpec(typeResolver).copy(isAbstract = true) } +
            openMethods.map { it.toMethodSpec(typeResolver).copy(isAbstract = false) }
    val propertySpecs =
        abstractProperties.map { it.toPropertySpec(typeResolver).copy(isAbstract = true) } +
            openProperties.map { it.toPropertySpec(typeResolver).copy(isAbstract = false) }
    return methodSpecs to propertySpecs
}
