// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.snapshotsmoke

import kotlin.test.Test
import kotlin.test.assertEquals

/** Uses the fake generated by the SNAPSHOT plugin — proof the whole pipeline resolves and runs. */
class GreeterTest {
    @Test
    fun `GIVEN fake greeter WHEN configured THEN returns configured value`() {
        val greeter = fakeGreeter { greet { name -> "Hi, $name!" } }
        assertEquals("Hi, Ada!", greeter.greet("Ada"))
    }
}
