// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.codegen.model

/**
 * Represents a complete Kotlin source file.
 *
 * Immutable value object - all mutations produce new instances.
 *
 * Example:
 * ```kotlin
 * val file = CodeFile("com.example")
 *     .addImport("kotlin.collections.List")
 *     .addDeclaration(CodeClass("MyClass"))
 * ```
 *
 * @property packageName The package declaration for this file
 * @property imports Set of fully-qualified import statements
 * @property declarations Top-level declarations (classes, functions, properties)
 * @property header Optional header comment (e.g., "Generated by Fakt")
 * @property fileAnnotations File-level annotations (e.g., @file:OptIn, @file:Suppress)
 */
data class CodeFile(
    val packageName: String,
    val imports: Set<String> = emptySet(),
    val declarations: List<CodeDeclaration> = emptyList(),
    val header: String? = null,
    val fileAnnotations: List<CodeAnnotation> = emptyList(),
) {
    /**
     * Adds a top-level declaration. Returns new CodeFile instance (immutable).
     *
     * TODO Phase 10: Alternative mutation API (currently builders are preferred).
     */
    fun addDeclaration(declaration: CodeDeclaration): CodeFile =
        copy(declarations = declarations + declaration)

    /**
     * Adds an import statement. Returns new CodeFile instance (immutable). Automatically
     * deduplicates imports.
     *
     * TODO Phase 10: Alternative mutation API (currently builders are preferred).
     */
    fun addImport(fqName: String): CodeFile = copy(imports = imports + fqName)
}

/** Base interface for all code declarations (classes, functions, properties). */
sealed interface CodeDeclaration

/** Marker interface for class members (properties, functions, comments). */
sealed interface CodeMember

/**
 * Represents a comment in generated code.
 *
 * Used for section headers and documentation within class bodies.
 *
 * @property text The comment text (without // prefix)
 */
data class CodeComment(val text: String) : CodeMember

/**
 * Represents a region start marker in generated code.
 *
 * Used for collapsible sections in IDEs (IntelliJ, Android Studio).
 *
 * @property name The region name displayed when collapsed
 */
data class CodeRegionStart(val name: String) : CodeMember

/** Represents a region end marker in generated code. */
data object CodeRegionEnd : CodeMember

/**
 * Represents a Kotlin class declaration.
 *
 * @property name The class name
 * @property typeParameters Generic type parameters (e.g., `<T, U>`)
 * @property superTypes Interfaces/classes this class implements/extends
 * @property modifiers Class modifiers (internal, abstract, etc.)
 * @property members Properties and functions within the class
 * @property constructorProperties Primary constructor properties (e.g., `class Foo(private val x:
 *   Int)`)
 * @property whereClause Optional where clause for complex constraints
 */
data class CodeClass(
    val name: String,
    val typeParameters: List<CodeTypeParameter> = emptyList(),
    val superTypes: List<CodeType> = emptyList(),
    val modifiers: Set<CodeModifier> = emptySet(),
    val members: List<CodeMember> = emptyList(),
    val constructorProperties: List<ConstructorProperty> = emptyList(),
    val whereClause: String? = null,
    val annotations: List<CodeAnnotation> = emptyList(),
) : CodeDeclaration {
    /**
     * Adds a member to this class. Returns new CodeClass instance (immutable).
     *
     * TODO Phase 10: Alternative mutation API (currently ClassBuilder is preferred).
     */
    fun addMember(member: CodeMember): CodeClass = copy(members = members + member)
}

/**
 * Represents a primary constructor property.
 *
 * Example: `class Foo(private val calls: List<Bar>)` -> ConstructorProperty("calls", "List<Bar>",
 * private)
 *
 * @property name Property name
 * @property type Property type as string
 * @property modifiers Property modifiers (private, public, etc.)
 */
data class ConstructorProperty(
    val name: String,
    val type: String,
    val modifiers: Set<CodeModifier> = emptySet(),
    val defaultValue: String? = null,
    val isMutable: Boolean = false,
    val isPlainParam: Boolean = false,
)

/**
 * Represents a Kotlin data class declaration.
 *
 * Data classes are primarily used for call history recording, where each method call's arguments
 * are captured as a data class instance.
 *
 * Example:
 * ```kotlin
 * data class UserServiceGetUserCall(val id: String, val includeDeleted: Boolean)
 * ```
 *
 * @property name The data class name
 * @property properties Constructor properties (all val)
 * @property modifiers Visibility modifiers (public, internal, etc.)
 * @property annotations Class-level annotations
 */
data class CodeDataClass(
    val name: String,
    val properties: List<DataClassProperty>,
    val modifiers: Set<CodeModifier> = emptySet(),
    val annotations: List<CodeAnnotation> = emptyList(),
) : CodeDeclaration

/**
 * Represents a property in a data class constructor.
 *
 * @property name Property name
 * @property type Property type as a string (will be parsed during rendering)
 */
data class DataClassProperty(val name: String, val type: String)

/**
 * Represents a Kotlin function (top-level or member).
 *
 * @property name Function name
 * @property parameters Function parameters
 * @property returnType Return type
 * @property body Function body (expression or statements)
 * @property modifiers Function modifiers (override, suspend, etc.)
 * @property typeParameters Generic type parameters
 * @property isSuspend Whether this is a suspend function
 * @property isInline Whether this is an inline function
 * @property receiverType Extension receiver type for extension functions (e.g., Vector for fun
 *   Vector.plus())
 * @property annotations Function-level annotations (e.g., @Suppress)
 * @property kdoc Optional KDoc documentation for the function
 * @property compact When true, suppresses the blank line before this function in class rendering
 */
data class CodeFunction(
    val name: String,
    val parameters: List<CodeParameter> = emptyList(),
    val returnType: CodeType,
    val body: CodeBlock,
    val modifiers: Set<CodeModifier> = emptySet(),
    val typeParameters: List<CodeTypeParameter> = emptyList(),
    val isSuspend: Boolean = false,
    val isInline: Boolean = false,
    val receiverType: CodeType? = null,
    val annotations: List<CodeAnnotation> = emptyList(),
    val whereClause: String? = null,
    val kdoc: String? = null,
    val compact: Boolean = false,
) : CodeDeclaration, CodeMember

/**
 * Represents a Kotlin property (top-level or member).
 *
 * @property name Property name
 * @property type Property type
 * @property modifiers Property modifiers (private, override, etc.)
 * @property initializer Optional initializer expression
 * @property getter Optional custom getter
 * @property setter Optional custom setter
 * @property isMutable Whether this is a var (true) or val (false)
 * @property annotations Property-level annotations (e.g., @PublishedApi)
 * @property compact When true, suppresses the blank line before this property in class rendering
 */
data class CodeProperty(
    val name: String,
    val type: CodeType,
    val modifiers: Set<CodeModifier> = emptySet(),
    val initializer: CodeExpression? = null,
    val getter: CodeBlock? = null,
    val setter: CodeBlock? = null,
    val isMutable: Boolean = false,
    val annotations: List<CodeAnnotation> = emptyList(),
    val compact: Boolean = false,
) : CodeDeclaration, CodeMember

/**
 * Function/property parameter.
 *
 * @property name Parameter name
 * @property type Parameter type
 * @property defaultValue Optional default value
 * @property isVararg Whether this is a vararg parameter
 */
data class CodeParameter(
    val name: String,
    val type: CodeType,
    val defaultValue: CodeExpression? = null,
    val isVararg: Boolean = false,
)

/**
 * Type parameter with optional constraints.
 *
 * Examples:
 * - `T` → CodeTypeParameter("T")
 * - `T : Comparable<T>` → CodeTypeParameter("T", listOf("Comparable<T>"))
 * - `out T` → CodeTypeParameter("T", variance = Variance.OUT)
 *
 * @property name Type parameter name
 * @property constraints Type constraints (e.g., `Comparable<T>`)
 * @property isReified Whether this is a reified type parameter
 * @property variance Variance modifier (in, out, or invariant)
 */
data class CodeTypeParameter(
    val name: String,
    val constraints: List<String> = emptyList(),
    val isReified: Boolean = false,
    val variance: Variance = Variance.INVARIANT,
) {
    enum class Variance {
        IN,
        OUT,
        INVARIANT,
    }
}

/**
 * Represents a type in Kotlin code.
 *
 * Examples:
 * - `String` → CodeType.Simple("String")
 * - `List<User>` → CodeType.Generic("List", listOf(CodeType.Simple("User")))
 * - `String?` → CodeType.Nullable(CodeType.Simple("String"))
 * - `(String) -> Int` → CodeType.Lambda(...)
 */
sealed interface CodeType {
    /** Simple type reference (e.g., String, User, Int). */
    data class Simple(val name: String) : CodeType

    /** Generic type with type arguments (e.g., List<String>, Map<String, Int>). */
    data class Generic(val name: String, val arguments: List<CodeType>) : CodeType

    /** Nullable type (e.g., String?, User?). */
    data class Nullable(val inner: CodeType) : CodeType

    /**
     * Lambda/function type (e.g., (String) -> Int, suspend (User) -> Unit).
     *
     * TODO Phase 10: Will be used for behavior properties like var getUserBehavior: (String) ->
     * User?.
     */
    data class Lambda(
        val parameters: List<CodeType>,
        val returnType: CodeType,
        val isSuspend: Boolean = false,
    ) : CodeType
}

/** Code modifiers (public, private, override, etc). */
enum class CodeModifier {
    PUBLIC,
    PRIVATE,
    INTERNAL,
    PROTECTED,
    OVERRIDE,
    OPEN,
    ABSTRACT,
    FINAL,
    SUSPEND,
    INLINE,
    OPERATOR,
    INFIX,
}

/** Represents a block of code (function body, getter, etc). */
sealed interface CodeBlock {
    /** Single expression: `= value` */
    data class Expression(val expr: CodeExpression) : CodeBlock

    /** Statement block: `{ statements }` */
    data class Statements(val statements: List<String>) : CodeBlock

    /** Empty block (for abstract members). */
    object Empty : CodeBlock
}

/** Represents an expression in code. */
sealed interface CodeExpression {
    /** String literal: "hello" */
    data class StringLiteral(val value: String) : CodeExpression

    /** Number literal: 42, 3.14 */
    data class NumberLiteral(val value: String) : CodeExpression

    /** Lambda: { it -> it * 2 } */
    data class Lambda(val parameters: List<String>, val body: String) : CodeExpression

    /** Function call: emptyList() */
    data class FunctionCall(val name: String, val arguments: List<CodeExpression> = emptyList()) :
        CodeExpression

    /** Raw code (escape hatch). */
    data class Raw(val code: String) : CodeExpression
}

/**
 * Represents an annotation on a declaration.
 *
 * Examples:
 * - `@OptIn(ExperimentalApi::class)` → CodeAnnotation("OptIn", listOf("ExperimentalApi::class"))
 * - `@Deprecated("old")` → CodeAnnotation("Deprecated", listOf("\"old\""))
 * - `@Suppress("UNCHECKED_CAST")` → CodeAnnotation("Suppress", listOf("\"UNCHECKED_CAST\""))
 *
 * @property name Annotation simple name (e.g., "OptIn", "Deprecated")
 * @property arguments Pre-rendered argument strings (e.g., "ExperimentalApi::class", "\"old\"")
 */
data class CodeAnnotation(val name: String, val arguments: List<String> = emptyList())
