// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.codegen.generator

import com.rsicarelli.fakt.codegen.analysis.FakeDeclaration
import com.rsicarelli.fakt.codegen.analysis.toAnnotationSpec
import com.rsicarelli.fakt.codegen.analysis.toCodegenSpecs
import com.rsicarelli.fakt.codegen.builder.parseType
import com.rsicarelli.fakt.codegen.extensions.FactoryFunctionSpec
import com.rsicarelli.fakt.codegen.extensions.generateCallHistoryDeclarations
import com.rsicarelli.fakt.codegen.extensions.generateCompleteFake
import com.rsicarelli.fakt.codegen.extensions.generateFactoryFunctionCodeFile
import com.rsicarelli.fakt.codegen.model.CodeFile
import com.rsicarelli.fakt.codegen.renderer.render
import com.rsicarelli.fakt.codegen.strategy.DefaultValueResolver

/**
 * @property implementationFile package + imports + implementation class + call-history components.
 * @property factoryFunction the `fakeXxx { ... }` factory function.
 */
public data class GeneratedFakeCode(val implementationFile: CodeFile, val factoryFunction: CodeFile)

/**
 * Implementation generator for fake classes and factory functions.
 *
 * Consumes the pure [FakeDeclaration] contract; types arrive pre-rendered, so no `TypeResolution`
 * dependency is needed.
 */
public class ImplementationGenerator {
    /**
     * Generates the fake implementation and factory for an interface.
     *
     * @param imports Additional FQNs to import — typically the resolved set returned by the
     *   compiler-side ImportResolver.
     */
    public fun generateImplementation(
        decl: FakeDeclaration.Interface,
        packageName: String,
        imports: List<String> = emptyList(),
    ): GeneratedFakeCode {
        val (methods, properties) = decl.toCodegenSpecs()
        val annotationSpecs = decl.annotations.map { it.toAnnotationSpec() }

        var implementationFile =
            generateCompleteFake(
                packageName = packageName,
                interfaceName = decl.simpleName,
                superTypeName = decl.qualifiedSourceName,
                methods = methods,
                properties = properties,
                imports = imports,
                header = "Generated by Fakt\n// Interface: ${decl.qualifiedSourceName}",
                typeParameters = decl.typeParameters,
                visibility = decl.visibility,
                annotations = annotationSpecs,
                generateCallHistory = decl.generateCallHistory,
                generateMutableBehaviors = decl.generateMutableBehaviors,
            )

        val factoryFunction =
            generateFactoryFunctionCodeFile(
                FactoryFunctionSpec(
                    interfaceName = decl.simpleName,
                    superTypeName = decl.qualifiedSourceName,
                    typeParameters = decl.typeParameters,
                    visibility = decl.visibility,
                    annotations = annotationSpecs,
                    methods = methods,
                    properties = properties,
                )
            )

        if (decl.generateCallHistory) {
            val fakeClassName = "Fake${decl.simpleName}Impl"
            val callHistoryDeclarations =
                generateCallHistoryDeclarations(
                    fakeClassName = fakeClassName,
                    interfaceName = decl.simpleName,
                    methods = methods,
                    visibility = decl.visibility,
                    classTypeParameters = decl.typeParameters,
                )
            callHistoryDeclarations.forEach { declaration ->
                implementationFile = implementationFile.addDeclaration(declaration)
            }
        }

        return GeneratedFakeCode(
            implementationFile = implementationFile,
            factoryFunction = factoryFunction,
        )
    }

    /**
     * Generates the fake implementation and factory for an abstract or open class.
     *
     * @param imports Additional FQNs to import — typically the resolved set returned by the
     *   compiler-side ImportResolver.
     */
    public fun generateClassFake(
        decl: FakeDeclaration.Class,
        packageName: String,
        imports: List<String> = emptyList(),
    ): GeneratedFakeCode {
        val (methodSpecs, propertySpecs) = decl.toCodegenSpecs()
        val annotationSpecs = decl.annotations.map { it.toAnnotationSpec() }
        val superConstructorCall = buildSuperConstructorCall(decl)

        var implementationFile =
            generateCompleteFake(
                packageName = packageName,
                interfaceName = decl.simpleName,
                superTypeName = decl.qualifiedSourceName,
                methods = methodSpecs,
                properties = propertySpecs,
                imports = imports,
                header = "Generated by Fakt\n// Class: ${decl.qualifiedSourceName}",
                typeParameters = decl.typeParameters,
                isClass = true,
                visibility = decl.visibility,
                annotations = annotationSpecs,
                generateCallHistory = decl.generateCallHistory,
                generateMutableBehaviors = decl.generateMutableBehaviors,
                superConstructorCall = superConstructorCall,
            )

        val factoryFunction =
            generateFactoryFunctionCodeFile(
                FactoryFunctionSpec(
                    interfaceName = decl.simpleName,
                    superTypeName = decl.qualifiedSourceName,
                    typeParameters = decl.typeParameters,
                    visibility = decl.visibility,
                    annotations = annotationSpecs,
                    methods = methodSpecs,
                    properties = propertySpecs,
                )
            )

        if (decl.generateCallHistory) {
            val fakeClassName = "Fake${decl.simpleName}Impl"
            val callHistoryDeclarations =
                generateCallHistoryDeclarations(
                    fakeClassName = fakeClassName,
                    interfaceName = decl.simpleName,
                    methods = methodSpecs,
                    visibility = decl.visibility,
                    classTypeParameters = decl.typeParameters,
                )
            callHistoryDeclarations.forEach { declaration ->
                implementationFile = implementationFile.addDeclaration(declaration)
            }
        }

        return GeneratedFakeCode(
            implementationFile = implementationFile,
            factoryFunction = factoryFunction,
        )
    }

    /**
     * Builds the `super(...)` constructor argument string for abstract-class fakes. Required params
     * (no default) get a default value derived from [DefaultValueResolver]; params that already
     * have a default are omitted (the class's own default applies).
     */
    private fun buildSuperConstructorCall(decl: FakeDeclaration.Class): String {
        val params = decl.constructorParameters.filter { !it.hasDefault }
        if (params.isEmpty()) return ""

        val resolver = DefaultValueResolver()
        return params.joinToString(", ") { param ->
            val parsedType = parseType(param.typeString)
            val defaultExpr = resolver.resolve(parsedType).render()
            "${param.name} = $defaultExpr"
        }
    }
}
