name: Test Samples
description: Test all sample projects to validate end-to-end functionality

runs:
  using: composite
  steps:
    # Publish Fakt plugin to Maven Local so samples can use it
    # Samples reference the plugin by ID and version (com.rsicarelli.fakt:1.0.0-alpha01)
    # which requires the plugin to be published before sample tests can run
    # Skip signing since we're only publishing locally for testing (no GPG credentials needed)
    - name: Publish Fakt plugin to Maven Local
      shell: bash
      env:
        ORG_GRADLE_PROJECT_SKIP_SIGNING: true
      run: ./gradlew publishToMavenLocal

    # Test JVM-only sample
    - name: Test jvm-single-module sample
      shell: bash
      run: ./gradlew -p samples/jvm-single-module build

    # Test Android sample
    - name: Test android-single-module sample
      shell: bash
      run: ./gradlew -p samples/android-single-module build

    # Using 'allTests' to ensure ALL KMP targets are tested (jvmTest, jsTest, etc.)
    # Then 'check' for additional validations (apiCheck, compilation validation).

    - name: Test kmp-single-module sample (all targets)
      shell: bash
      run: ./gradlew -p samples/kmp-single-module allTests --continue

    - name: Check kmp-single-module sample (validations)
      shell: bash
      run: ./gradlew -p samples/kmp-single-module check

    - name: Test kmp-multi-module sample (all targets)
      shell: bash
      run: ./gradlew -p samples/kmp-multi-module allTests --continue

    - name: Check kmp-multi-module sample (validations)
      shell: bash
      run: ./gradlew -p samples/kmp-multi-module check

    - name: Publish sample test results
      if: success() || failure()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: 'samples/**/build/test-results/**/*.xml'
        check_name: Sample Test Results
