name: ðŸ› Bug Report
description: Report a bug in Fakt
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the information below to help us investigate.

  - type: input
    id: fakt-version
    attributes:
      label: Fakt Version
      description: Which version of Fakt are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: kotlin-version
    attributes:
      label: Kotlin Version
      description: Which version of Kotlin are you using?
      placeholder: "e.g., 2.2.21"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you targeting?
      options:
        - Kotlin Multiplatform (KMP)
        - JVM only
        - Android only
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Describe the issue including:
        - What's happening vs what you expected
        - Steps to reproduce
        - Minimal code example
        - Error message and build logs (with DEBUG logging if possible)
      placeholder: |
        **What's happening:**
        When I annotate my interface with @Fake, I expected the fake to compile but the build fails.

        **How to reproduce:**
        1. Create interface with @Fake annotation
        2. Run `./gradlew build`
        3. See error...

        **Code example:**
        ```kotlin
        @Fake
        interface MyService {
            fun doSomething(): String
        }
        ```

        **Error / Build logs:**
        ```
        ./gradlew build --info

        > Task :compileKotlin FAILED
        e: Error message here...
        ```

        **DEBUG logging (optional but helpful):**
        Add to build.gradle.kts:
        ```kotlin
        fakt {
            logLevel.set(LogLevel.DEBUG)
        }
        ```
    validations:
      required: true

  - type: input
    id: gradle-version
    attributes:
      label: Gradle Version
      placeholder: "e.g., 8.4"
    validations:
      required: false

  - type: input
    id: kmp-targets
    attributes:
      label: KMP Targets (if KMP selected above)
      description: Which KMP targets are you using?
      placeholder: "e.g., jvm, iosArm64, iosSimulatorArm64, js"
    validations:
      required: false

  - type: checkboxes
    id: module-setup
    attributes:
      label: Module Setup
      options:
        - label: Single-module
        - label: Multi-module

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
