name: 🐛 Bug Report
description: Report a bug in Fakt
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the information below to help us investigate.

  - type: input
    id: fakt-version
    attributes:
      label: Fakt Version
      description: Which version of Fakt are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: kotlin-version
    attributes:
      label: Kotlin Version
      description: Which version of Kotlin are you using?
      placeholder: "e.g., 2.2.21"
    validations:
      required: true

  - type: dropdown
    id: project-type
    attributes:
      label: Project Type
      description: How is your project structured?
      options:
        - Single-module JVM/Android
        - Multiplatform (KMP)
        - Multi-module setup
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What's happening?
      description: Describe the bug and what you expected to happen
      placeholder: |
        When I annotate my interface with @Fake, I expected X but got Y.

        Expected: The fake should compile
        Actual: Build fails with error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Create interface with @Fake
        2. Run `./gradlew build`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: platform-info
    attributes:
      label: Platform Info (optional)
      description: For KMP projects - Gradle version and targets
      placeholder: |
        Gradle: 8.4
        Targets: jvm, iosArm64, iosSimulatorArm64
    validations:
      required: false

  - type: textarea
    id: logs-and-reproduction
    attributes:
      label: Build Logs & Minimal Reproduction
      description: |
        To diagnose the issue, please include:
        1. Minimal reproduction code (interface + usage)
        2. Error message / stack trace
        3. Build logs with DEBUG logging enabled:
           ```kotlin
           fakt {
               logLevel.set(LogLevel.DEBUG)
           }
           ```
        4. Full build output: `./gradlew build --info`

        See [Troubleshooting Guide](https://rsicarelli.github.io/fakt/help/troubleshooting/)
      render: shell
      placeholder: |
        @Fake
        interface MyService {
            fun doSomething(): String
        }

        // Build output:
        ./gradlew build --info
        ...
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
