name: 💡 Feature Request
description: Suggest a new feature for Fakt (we love hearing your ideas!)
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## We Want to Hear Your Ideas! 🚀

        Feature requests from the community often shape our roadmap.
        Your feedback helps make Fakt better for everyone!

        **Before submitting:**
        - 🔍 Search existing issues to avoid duplicates

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem or limitation you're facing
      placeholder: "I often need to... but currently Fakt doesn't support..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      render: kotlin
      placeholder: |
        // I'd like to be able to:
        @Fake
        interface MyService<T> {
            fun get(): T
        }

        val fake = fakeMyService<String> {
            onGet { "test" }
        }
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you targeting?
      options:
        - Kotlin Multiplatform (KMP)
        - JVM only
        - Android only
    validations:
      required: false

  - type: checkboxes
    id: module-setup
    attributes:
      label: Module Setup
      options:
        - label: Single-module
        - label: Multi-module

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
