// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.codegen.compilation

import com.rsicarelli.fakt.codegen.builder.codeFile
import com.rsicarelli.fakt.codegen.renderer.CodeBuilder
import com.rsicarelli.fakt.codegen.renderer.renderTo
import org.junit.jupiter.api.TestInstance
import kotlin.test.Test

/**
 * Compilation validation tests for generated fake code.
 *
 * Uses kotlin-compile-testing to ensure all generated code actually compiles.
 * This is critical for catching type errors, import issues, and syntax problems
 * before integrating with the real compiler.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class GeneratedCodeCompilationTest : CompilationTestBase() {
    @Test
    fun `GIVEN simple fake implementation WHEN compiling THEN succeeds`() {
        // GIVEN
        val code =
            """
            package com.example

            interface UserService {
                fun getUser(id: String): String?
            }

            class FakeUserServiceImpl : UserService {
                private var getUserBehavior: (String) -> String? = { null }

                override fun getUser(id: String): String? {
                    return getUserBehavior(id)
                }
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(code, "Simple fake implementation")
    }

    @Test
    fun `GIVEN fake with collections WHEN compiling THEN succeeds`() {
        // GIVEN
        val code =
            """
            package com.example

            data class User(val name: String)

            interface Repository {
                fun findAll(): List<User>
                fun findById(id: String): User?
            }

            class FakeRepositoryImpl : Repository {
                private var findAllBehavior: () -> List<User> = { emptyList() }
                private var findByIdBehavior: (String) -> User? = { null }

                override fun findAll(): List<User> {
                    return findAllBehavior()
                }

                override fun findById(id: String): User? {
                    return findByIdBehavior(id)
                }
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(code, "Fake with collections")
    }

    @Test
    fun `GIVEN fake with StateFlow WHEN compiling THEN succeeds`() {
        // GIVEN
        val code =
            """
            package com.example

            import kotlinx.coroutines.flow.StateFlow
            import kotlinx.coroutines.flow.MutableStateFlow

            data class User(val name: String)

            interface UserStore {
                val users: StateFlow<List<User>>
            }

            class FakeUserStoreImpl : UserStore {
                private val usersValue: StateFlow<List<User>> = MutableStateFlow(emptyList())

                override val users: StateFlow<List<User>>
                    get() = usersValue
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(code, "Fake with StateFlow")
    }

    @Test
    fun `GIVEN fake with suspend functions WHEN compiling THEN succeeds`() {
        // GIVEN
        val code =
            """
            package com.example

            data class User(val name: String)

            interface AsyncService {
                suspend fun fetchUser(id: String): User?
                suspend fun saveUser(user: User): Result<Unit>
            }

            class FakeAsyncServiceImpl : AsyncService {
                private var fetchUserBehavior: suspend (String) -> User? = { null }
                private var saveUserBehavior: suspend (User) -> Result<Unit> = { Result.success(Unit) }

                override suspend fun fetchUser(id: String): User? {
                    return fetchUserBehavior(id)
                }

                override suspend fun saveUser(user: User): Result<Unit> {
                    return saveUserBehavior(user)
                }
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(code, "Fake with suspend functions")
    }

    @Test
    fun `GIVEN complete fake generated by DSL WHEN compiling THEN succeeds`() {
        // GIVEN - Use actual DSL to generate code
        val file =
            codeFile("com.example") {
                klass("FakeServiceImpl") {
                    implements("Service")

                    property("doSomethingBehavior", "() -> String") {
                        private()
                        mutable()
                        initializer = "{ \"\" }"
                    }

                    function("doSomething") {
                        override()
                        returns("String")
                        body = "return doSomethingBehavior()"
                    }
                }
            }

        val builder = CodeBuilder()
        file.renderTo(builder)
        val generatedCode = builder.build()

        // Add interface definition
        val completeCode =
            """
            $generatedCode

            interface Service {
                fun doSomething(): String
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(completeCode, "DSL-generated fake")
    }

    @Test
    fun `GIVEN fake with complex nested types WHEN compiling THEN succeeds`() {
        // GIVEN
        val code =
            """
            package com.example

            import kotlinx.coroutines.flow.StateFlow
            import kotlinx.coroutines.flow.MutableStateFlow

            data class User(val name: String)

            interface ComplexService {
                fun getMap(): Map<String, List<User>>
                val state: StateFlow<Map<String, List<User>>>
            }

            class FakeComplexServiceImpl : ComplexService {
                private var getMapBehavior: () -> Map<String, List<User>> = { emptyMap() }
                private val stateValue: StateFlow<Map<String, List<User>>> = MutableStateFlow(emptyMap())

                override fun getMap(): Map<String, List<User>> {
                    return getMapBehavior()
                }

                override val state: StateFlow<Map<String, List<User>>>
                    get() = stateValue
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(code, "Fake with nested generics")
    }

    @Test
    fun `GIVEN fake with vararg parameters WHEN compiling THEN succeeds`() {
        // GIVEN
        val code =
            """
            package com.example

            interface Service {
                fun process(vararg items: String): Int
            }

            class FakeServiceImpl : Service {
                private var processBehavior: (Array<out String>) -> Int = { 0 }

                override fun process(vararg items: String): Int {
                    return processBehavior(items)
                }
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(code, "Fake with vararg")
    }

    @Test
    fun `GIVEN fake with default parameters WHEN compiling THEN succeeds`() {
        // GIVEN
        val code =
            """
            package com.example

            interface Service {
                fun process(value: String = "", count: Int = 0): Unit
            }

            class FakeServiceImpl : Service {
                private var processBehavior: (String, Int) -> Unit = { _, _ -> Unit }

                override fun process(value: String, count: Int): Unit {
                    return processBehavior(value, count)
                }
            }
            """.trimIndent()

        // WHEN/THEN
        assertCompiles(code, "Fake with default parameters")
    }
}
