// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.samples.kmpNoJvm

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Drives the commonTest fake generated by the no-JVM-target producer. If the producer failed on
 * the unpaired `expect` (the issue #79 blocker) or never ran, this file would not compile.
 */
class DeviceRegistryTest {

    @Test
    fun `GIVEN DeviceRegistry fake WHEN registering THEN configured behavior and call tracking work`() {
        // Given
        val fake = fakeDeviceRegistry { register { name -> name.isNotEmpty() } }

        // When
        val added = fake.register("sensor-1")

        // Then
        assertTrue(added)
        assertEquals(1, fake.registerCalls.value.size)
    }

    @Test
    fun `GIVEN DeviceRegistry fake WHEN using defaults THEN sensible defaults apply`() {
        // Given
        val fake = fakeDeviceRegistry()

        // When
        val found = fake.find(42)
        val count = fake.deviceCount

        // Then
        assertNull(found)
        assertEquals(0, count)
        assertEquals(1, fake.findCalls.value.size)
    }

    @Test
    fun `GIVEN platform actual WHEN resolving currentPlatform THEN expect declaration is satisfied at runtime`() {
        // The expect/actual pair itself must keep working end-to-end on every target.
        assertTrue(currentPlatform().isNotEmpty())
    }
}
