// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.samples.kmpNoJvm

import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Drives the jsTest fake generated by the in-process plugin (LEGACY_HYBRID path) — platform
 * `@Fake` declarations must keep working in a project with no drivable target.
 */
class JsOnlyStorageTest {

    @Test
    fun `GIVEN JsOnlyStorage fake WHEN getting a configured key THEN returns configured value`() {
        // Given
        val fake = fakeJsOnlyStorage { get { key -> "value-for-$key" } }

        // When
        val value = fake.get("session")

        // Then
        assertEquals("value-for-session", value)
        assertEquals(1, fake.getCalls.value.size)
    }
}
