// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.codegen.builder

import com.rsicarelli.fakt.codegen.model.CodeClass
import com.rsicarelli.fakt.codegen.model.CodeFunction
import com.rsicarelli.fakt.codegen.model.CodeProperty
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Tests for CodeFileBuilder DSL.
 *
 * CodeFileBuilder provides a type-safe DSL for building code files.
 */
class CodeFileBuilderTest {
    @Test
    fun `GIVEN codeFile DSL WHEN building empty file THEN creates CodeFile`() {
        // GIVEN/WHEN
        val file =
            codeFile("com.example") {
                // Empty
            }

        // THEN
        assertEquals("com.example", file.packageName)
        assertTrue(file.declarations.isEmpty())
    }

    @Test
    fun `GIVEN codeFile DSL WHEN adding imports THEN collects imports`() {
        // GIVEN/WHEN
        val file =
            codeFile("com.example") {
                import("com.example.User")
                import("kotlinx.coroutines.flow.StateFlow")
            }

        // THEN
        assertEquals(2, file.imports.size)
        assertTrue(file.imports.contains("com.example.User"))
        assertTrue(file.imports.contains("kotlinx.coroutines.flow.StateFlow"))
    }

    @Test
    fun `GIVEN codeFile DSL WHEN adding class THEN creates CodeClass`() {
        // GIVEN/WHEN
        val file =
            codeFile("com.example") {
                klass("MyClass") {
                    // Empty class
                }
            }

        // THEN
        assertEquals(1, file.declarations.size)
        val clazz = file.declarations[0] as CodeClass
        assertEquals("MyClass", clazz.name)
    }

    @Test
    fun `GIVEN codeFile DSL WHEN building complete file THEN creates full structure`() {
        // GIVEN/WHEN
        val file =
            codeFile("com.example") {
                header = "Generated by Fakt"
                import("com.example.User")

                klass("FakeUserServiceImpl") {
                    implements("UserService")

                    property("value", "String") {
                        private()
                        initializer = "\"\""
                    }

                    function("getUser") {
                        override()
                        parameter("id", "String")
                        returns("User?")
                        body = "return null"
                    }
                }
            }

        // THEN
        assertEquals("com.example", file.packageName)
        assertEquals("Generated by Fakt", file.header)
        assertEquals(1, file.imports.size)
        assertEquals(1, file.declarations.size)

        val clazz = file.declarations[0] as CodeClass
        assertEquals("FakeUserServiceImpl", clazz.name)
        assertEquals(1, clazz.superTypes.size)
        assertEquals(2, clazz.members.size)

        // Verify property
        val prop = clazz.members[0] as CodeProperty
        assertEquals("value", prop.name)
        assertNotNull(prop.initializer)

        // Verify function
        val func = clazz.members[1] as CodeFunction
        assertEquals("getUser", func.name)
        assertEquals(1, func.parameters.size)
    }

    @Test
    fun `GIVEN codeFile DSL WHEN adding multiple classes THEN creates all`() {
        // GIVEN/WHEN
        val file =
            codeFile("com.example") {
                klass("First") {}
                klass("Second") {}
                klass("Third") {}
            }

        // THEN
        assertEquals(3, file.declarations.size)
        assertEquals("First", (file.declarations[0] as CodeClass).name)
        assertEquals("Second", (file.declarations[1] as CodeClass).name)
        assertEquals("Third", (file.declarations[2] as CodeClass).name)
    }

    @Test
    fun `GIVEN codeFile DSL WHEN using imports vararg THEN adds all`() {
        // GIVEN/WHEN
        val file =
            codeFile("com.example") {
                imports(
                    "kotlinx.coroutines.flow.StateFlow",
                    "kotlinx.coroutines.flow.MutableStateFlow",
                    "com.example.User",
                )
            }

        // THEN
        assertEquals(3, file.imports.size)
    }
}
