// Copyright (C) 2025 Rodrigo Sicarelli
// SPDX-License-Identifier: Apache-2.0
package com.rsicarelli.fakt.codegen.builder

import com.rsicarelli.fakt.codegen.model.CodeAnnotation
import com.rsicarelli.fakt.codegen.model.CodeDeclaration
import com.rsicarelli.fakt.codegen.model.CodeFile

/**
 * DSL entry point for building code files.
 *
 * Provides a type-safe, fluent API for constructing Kotlin source files. Uses scope functions and
 * DSL markers to prevent scope leakage.
 *
 * Example:
 * ```kotlin
 * val file = codeFile("com.example") {
 *     header = "Generated by Fakt"
 *     import("kotlinx.coroutines.flow.StateFlow")
 *
 *     klass("FakeUserService") {
 *         implements("UserService")
 *         property("count", "Int") {
 *             private()
 *             initializer = "0"
 *         }
 *     }
 * }
 * ```
 *
 * @param packageName The package declaration for this file
 * @param block The DSL block for building file contents
 * @return An immutable [CodeFile] instance representing the code structure
 */
public inline fun codeFile(packageName: String, block: CodeFileBuilder.() -> Unit): CodeFile =
    CodeFileBuilder(packageName).apply(block).build()

/**
 * Builder for [CodeFile] using type-safe DSL.
 *
 * This class should not be instantiated directly. Use the [codeFile] function instead.
 *
 * @property packageName The package for this file
 */
@CodeDsl
public class CodeFileBuilder @PublishedApi internal constructor(private val packageName: String) {
    @PublishedApi internal val imports = mutableSetOf<String>()

    @PublishedApi internal val declarations = mutableListOf<CodeDeclaration>()

    @PublishedApi internal val fileAnnotations = mutableListOf<CodeAnnotation>()

    /** Optional header comment (e.g., "Generated by Fakt"). */
    public var header: String? = null

    /**
     * Adds a file-level annotation (e.g., @file:OptIn, @file:Suppress).
     *
     * Example:
     * ```kotlin
     * fileAnnotation("OptIn", "kotlin.experimental.ExperimentalObjCRefinement::class")
     * fileAnnotation("Suppress", "\"UNCHECKED_CAST\"")
     * ```
     *
     * @param name Annotation simple name (e.g., "OptIn", "Suppress")
     * @param arguments Pre-rendered argument strings
     */
    public fun fileAnnotation(name: String, vararg arguments: String) {
        fileAnnotations.add(CodeAnnotation(name, arguments.toList()))
    }

    /**
     * Adds import. Smart handling: skips auto-imported kotlin stdlib, deduplicates.
     *
     * Skips kotlin.* types that are auto-imported, but includes:
     * - kotlin.native.* (e.g., HiddenFromObjC) - not auto-imported
     * - kotlin.experimental.* (e.g., ExperimentalObjCRefinement) - not auto-imported
     * - kotlin.reflect.* (e.g., KClass) - not auto-imported
     *
     * @param fqName Fully-qualified class name to import
     */
    public fun import(fqName: String) {
        // Include kotlin.* types that are NOT auto-imported
        val alwaysInclude =
            fqName.startsWith("kotlin.native.") ||
                fqName.startsWith("kotlin.experimental.") ||
                fqName.startsWith("kotlin.reflect.")
        if (alwaysInclude || !fqName.startsWith("kotlin.")) {
            imports.add(fqName)
        }
    }

    /**
     * Adds multiple imports.
     *
     * @param fqNames Fully-qualified class names to import
     */
    public fun imports(vararg fqNames: String) {
        fqNames.forEach { import(it) }
    }

    /**
     * Builds a class declaration.
     *
     * Example:
     * ```kotlin
     * klass("FakeUserService") {
     *     implements("UserService")
     *     property("count", "Int") {
     *         initializer = "0"
     *     }
     * }
     * ```
     *
     * @param name The class name
     * @param block DSL block for configuring the class
     */
    public inline fun klass(name: String, block: ClassBuilder.() -> Unit) {
        declarations.add(ClassBuilder(name).apply(block).build())
    }

    /**
     * Builds a top-level function.
     *
     * Example:
     * ```kotlin
     * function("fakeUserService") {
     *     returns("UserService")
     *     body = "return FakeUserServiceImpl()"
     * }
     * ```
     *
     * TODO Phase 10: Will be used for top-level factory functions in generated fakes.
     *
     * @param name The function name
     * @param block DSL block for configuring the function
     */
    public inline fun function(name: String, block: FunctionBuilder.() -> Unit) {
        declarations.add(FunctionBuilder(name).apply(block).build())
    }

    /**
     * Builds a top-level data class declaration.
     *
     * Example:
     * ```kotlin
     * dataClass("UserServiceGetUserCall") {
     *     public()
     *     property("id", "String")
     *     property("includeDeleted", "Boolean")
     * }
     * ```
     *
     * @param name The data class name
     * @param block DSL block for configuring the data class
     */
    public inline fun dataClass(name: String, block: DataClassBuilder.() -> Unit) {
        declarations.add(DataClassBuilder(name).apply(block).build())
    }

    /**
     * Builds the final [CodeFile].
     *
     * @return Immutable [CodeFile] instance
     */
    @PublishedApi
    internal fun build(): CodeFile =
        CodeFile(
            packageName = packageName,
            imports = imports.toSet(),
            declarations = declarations.toList(),
            header = header,
            fileAnnotations = fileAnnotations.toList(),
        )
}

/**
 * DSL marker to prevent scope leakage.
 *
 * Ensures that DSL methods from outer scopes cannot be called in inner scopes. This provides
 * compile-time safety and better IDE autocomplete.
 */
@DslMarker public annotation class CodeDsl
